### ISSUE TITLE
Mongodb connection problem with lodex container

### ISSUE THREAD

**Issue by dieubenit** [Inist-CNRS/lodex#1440]
Hello, 

I deployed the lodex application under docker, everything works. Except the connection to the mongodb database which doesn't work. 
Your help will be welcome. 

attached log error :

``````
lodex-lodex-1       | 6:M 09 Jun 2022 12:30:24.005 * Ready to accept connections
lodex-mongo-1       | 2022-06-09T12:30:24.108+0000 W STORAGE  [initandlisten] Detected configuration for non-active storage engine mmapv1 when current storage engine is wiredTiger
lodex-mongo-1       | 2022-06-09T12:30:24.108+0000 I CONTROL  [initandlisten]
lodex-mongo-1       | 2022-06-09T12:30:24.108+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
lodex-mongo-1       | 2022-06-09T12:30:24.108+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
lodex-mongo-1       | 2022-06-09T12:30:24.108+0000 I CONTROL  [initandlisten]
lodex-mongo-1       | 2022-06-09T12:30:24.109+0000 I CONTROL  [initandlisten]
lodex-mongo-1       | 2022-06-09T12:30:24.109+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
lodex-mongo-1       | 2022-06-09T12:30:24.109+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
lodex-mongo-1       | 2022-06-09T12:30:24.109+0000 I CONTROL  [initandlisten]
lodex-mongo-1       | 2022-06-09T12:30:24.114+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
lodex-mongo-1       | 2022-06-09T12:30:24.114+0000 I NETWORK  [thread1] waiting for connections on port 27017
lodex-lodex-1       | 6:M 09 Jun 2022 12:30:25.000 * DB saved on disk
lodex-lodex-1       | OK
lodex-lodex-1       |
lodex-lodex-1       | > lodex@12.22.5 start /app
lodex-lodex-1       | > node --require @babel/register src/api
lodex-lodex-1       |
lodex-lodex-1       | Browserslist: caniuse-lite is outdated. Please run:
lodex-lodex-1       |   npx browserslist@latest --update-db
lodex-lodex-1       |   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
lodex-lodex-1       |
lodex-lodex-1       | WARNING (@babel/preset-env): We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.
lodex-lodex-1       |
lodex-lodex-1       | You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:
lodex-lodex-1       |
lodex-lodex-1       |   npm install --save core-js@2    npm install --save core-js@3
lodex-lodex-1       |   yarn add core-js@2              yarn add core-js@3
lodex-lodex-1       |
lodex-lodex-1       | More info about useBuiltIns: https://babeljs.io/docs/en/babel-preset-env#usebuiltins
lodex-lodex-1       | More info about core-js: https://babeljs.io/docs/en/babel-preset-env#corejs
lodex-lodex-1       | Thu, 09 Jun 2022 12:30:41 GMT koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md at src/api/index.js:92:5
lodex-lodex-1       | Server listening on port 3000
lodex-lodex-1       | Press CTRL+C to stop server
lodex-lodex-1       | Error [MongoError]: failed to connect to server [undefined:27017] on first connect [Error: getaddrinfo ENOTFOUND undefined

lodex-lodex-1       |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
lodex-lodex-1       |   name: 'MongoError'
lodex-lodex-1       | }]
lodex-lodex-1       |     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
lodex-lodex-1       |     at Pool.emit (events.js:314:20)
lodex-lodex-1       |     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
lodex-lodex-1       |     at Object.onceWrapper (events.js:421:26)
lodex-lodex-1       |     at Connection.emit (events.js:314:20)
lodex-lodex-1       |     at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:189:49)
lodex-lodex-1       |     at Object.onceWrapper (events.js:421:26)
lodex-lodex-1       |     at Socket.emit (events.js:314:20)
lodex-lodex-1       |     at emitErrorNT (internal/streams/destroy.js:92:8)
lodex-lodex-1       |     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
lodex-lodex-1       |     at processTicksAndRejections (internal/process/task_queues.js:84:21)
lodex-lodex-1       | (node:29) UnhandledPromiseRejectionWarning: Error: L'url de la base mongoDB n'est pas bonne, ou non renseignée.
lodex-lodex-1       |     at /app/src/api/services/mongoClient.js:16:19
lodex-lodex-1       |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
lodex-lodex-1       | (node:29) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
lodex-lodex-1       | (node:29) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^CGracefully stopping... (press Ctrl+C again to force)

``````

Thanks

**Comment by parmentf** [comment]
I think it's because of the first change in [version 12.22.5](https://github.com/Inist-CNRS/lodex/releases/tag/v12.22.5): #1412.

You now have to modify the configuration file ([config.json](https://github.com/Inist-CNRS/lodex/blob/master/config.json)) to add a `mongo.host` connection URI.

For example:

```json
{
	"mongo": {
		"host": "mongodb-server:27017"
	},
...
}
```

**Comment by dieubenit** [comment]
Hello,

Thank you for your answer, I have applied the solution in the config.json
file.
But I still have the error message.

[image: image.png]


Cordialement,
*____________________________________________________________________________________*
*Innocent Dieu Benit OUEFIO*
Ingénieur Système & Bases de données
Intégrateur d'application médicale

Email : ***@***.*** ***@***.***>*
Tel : +33 6 58 24 10 15
