### ISSUE TITLE
Cannot read properties of undefined (reading 'filter')

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/lodex#2174]
**Décrire le bogue**
message affiché par défaut au démarrage de l'instance

**Reproduire**
??

**Comportement attendu**
affichage de l'instance par défaut

**Captures d'écran**
![image](https://github.com/user-attachments/assets/e6205b99-1cdf-49d3-aefa-fa16345d227e)

**Environnement (veuillez compléter les informations suivantes) :**

- chrome
- Version de LODEX 14.0.62

**Contexte supplémentaire**
 TypeError: Cannot read properties of undefined (reading 'filter')
      at configTenantInstanceMiddleware (/app/src/api/controller/index.js:87:57)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at /app/src/api/services/repositoryMiddleware.js:27:5
      at /app/src/api/controller/index.js:58:9
      at /app/node_modules/koa-mount/index.js:52:26
      at mongoRootAdminClient (/app/src/api/services/repositoryMiddleware.js:38:5)

**Comment by touv** [comment]
à priori la configuration de l'instance ne contient plus les bonnes clés 
![image](https://github.com/user-attachments/assets/26d77900-ddcf-45fb-bb22-5ccd65f0a406)

**Comment by touv** [comment]
en modifiant la configuration directement dans la base pour ajouter "menu": [],
![image](https://github.com/user-attachments/assets/5548f54e-95c4-4801-b3c1-28da03f7d609)

on peut retrouver un comportement normal

**Comment by touv** [comment]
reste à éviter que la configuration casse l'instance, si on saisie un json qui n'est pas conforme aux attentes de lodex
