### ISSUE TITLE
Cannot read properties of undefined (reading 'startsWith')

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/lodex#2213]
**Décrire le bogue**
instance bloquée au démarrage, il est impossible d'afficher et d'accèder aux interfaces

**Reproduire**
inconnu 

**Captures d'écran**
![image](https://github.com/user-attachments/assets/2b8cbd82-91c8-4100-8c2d-bbd50d3618b8)

**Contexte supplémentaire**

```
 TypeError: Cannot read properties of undefined (reading 'startsWith')
      at BreadcrumbItem (/app/src/app/js/public/breadcrumb/BreadcrumbItem.js:40:19)
      at d (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:498)
      at $a (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
      at a.b.render (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
      at a.b.read (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
      at renderToString (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
      at /app/src/api/controller/front.js:125:23
      at Object.renderStatic (/app/node_modules/aphrodite/lib/exports.js:53:20)
      at getPreloadedState (/app/src/api/controller/front.js:124:22)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at handleRender (/app/src/api/controller/front.js:170:42)
      at /app/src/api/controller/front.js:244:16
      at /app/src/api/controller/front.js:230:16
      at /app/node_modules/koa-mount/index.js:52:26
      at /app/node_modules/koa-mount/index.js:52:26
      at /app/node_modules/koa-mount/index.js:52:26
      at configTenantInstanceMiddleware (/app/src/api/controller/index.js:117:5)
      at /app/src/api/services/repositoryMiddleware.js:27:5
      at /app/src/api/controller/index.js:73:5
      at /app/node_modules/koa-mount/index.js:52:26
      at mongoRootAdminClient (/app/src/api/services/repositoryMiddleware.js:38:5)
```

**Comment by touv** [comment]
see https://github.com/Inist-CNRS/lodex/blob/master/src/app/js/public/breadcrumb/BreadcrumbItem.js#L40

**Comment by touv** [comment]
![image](https://github.com/user-attachments/assets/9c4bd1e4-72b9-4f2a-b96d-bff4975cadca)

**Comment by touv** [comment]
le problème apparait quand il manque le champ url dans un item du "breadcrumb": []
