### ISSUE TITLE
14.0.67 Impossibilité de lancer les pré-calcul graph-segment et tree-segment sur une seule colonne

### ISSUE THREAD

**Issue by AnaelKremer** [Inist-CNRS/lodex#2262]
Dans la 14.0.67 les pré-calculs graph-segment (pour faire des réseaux) et tree-segment échouent avant l'étape 5 

![image](https://github.com/user-attachments/assets/6c5baf0e-d551-4cfb-928e-a44b93baf28c)

Il manquerait un champ selon le message d'erreur, en effet les pré-calculs se lancent bien si j'ajoute une seconde colonne source, sauf que l'on pouvait avant les lancer sur une seule colonne, ce qui est toujours possible dans la 14.0.66 >

![image](https://github.com/user-attachments/assets/86d16b1c-2145-43e6-9e80-13f1107dfc0f)

voici le message d'erreur développé : 
`handlePrecomputedError Error: Fatal run-time error (item #1    { value: [ 'The value field is required.' ] })
    at processPrecomputed (/app/src/api/services/precomputed/precomputed.js:443:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at startAskForPrecomputed (/app/src/api/services/precomputed/precomputed.js:497:5)
    at startJobPrecomputed (/app/src/api/workers/precomputer.js:35:9)`

EDIT : LE BUG NE SE PRODUIT PAS TOUT LE TEMPS...

J'ai pensé que "value field" pouvait peut être signifier des lignes vides dans la colonne, mais non, on peut lancer le précalcul sur une seule colonne qui contient des tableaux vides, et puis sur une autre colonne avec des données en tableau toujours on a de nouveau l'erreur.

**Comment by yannguillemin** [comment]
Effectivement, le bug ne se reproduit pas à chaque essai : le précalcul ci-dessous ne fonctionnait pas ce matin mais fonctionne maintenant.
![image](https://github.com/user-attachments/assets/77aa66b1-3e88-45eb-8c14-97b951a987bf)
