### ISSUE TITLE
Impossible de lancer des enrichissements ou de (re)publier

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/lodex#2289]
**Décrire le bogue**
 on clique sur le bouton lancer, rien ne se passe

- Version de 14.0.68

**Comment by touv** [comment]
La log
```
  TypeError: Cannot read properties of undefined (reading 'add')
      at Object.doPublish (/app/src/api/controller/api/publish.js:13:36)
      at /app/node_modules/koa-route/index.js:39:44
      at dispatch (/app/node_modules/koa-compose/index.js:42:32)
      at /app/node_modules/koa-compose/index.js:34:12
      at /app/node_modules/koa-mount/index.js:58:11
      at dispatch (/app/node_modules/koa-compose/index.js:42:32)
      at /app/node_modules/koa-mount/index.js:52:32
      ```

**Comment by AnaelKremer** [comment]
Le problème ne se pose que sur la machine de dev.
J'ai pu lancer un enrichissement sur une autre machine en version 67. Or, sur celle de dev, j'ai testé plusieurs instances en version 68, 67 et 66 rien ne se passe.

**Comment by touv** [comment]
en fait, c'est pas les enrichissements, la publication est bloquée également. j'ai redémarré lodex et ça remarche

**Comment by touv** [comment]
le système des taches de fond ne fonctionnait plus, reste à savoir pourquoi...
