### ISSUE TITLE
Error during CSV import

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/lodex#2291]
Vu dans log serveur :

```
Error during import Error: item #1 [CSVObject] <TypeError: data.map is not a function>
    at Engine.execWith (/app/node_modules/@ezs/core/lib/engine.js:209:23)
    at /app/node_modules/@ezs/core/lib/engine.js:83:12
    at drainItem (/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/app/node_modules/concurrent-queue/index.js:77:84)
    at processImmediate (node:internal/timers:476:21) {
  sourceError: TypeError: data.map is not a function
      at Object.CSVObject (/app/node_modules/@ezs/basics/lib/csv-object.js:12:25)
      at Engine.execWith (/app/node_modules/@ezs/core/lib/engine.js:202:40)
      at /app/node_modules/@ezs/core/lib/engine.js:83:12
      at drainItem (/app/node_modules/concurrent-queue/index.js:96:21)
      at Immediate.drain [as _onImmediate] (/app/node_modules/concurrent-queue/index.js:77:84)
      at processImmediate (node:internal/timers:476:21),
  sourceChunk: `{"lodex_published":"'lodex-published'"}`,
  type: 'Data corruption error',
  scope: 'data',
  date: 2024-12-20T08:48:54.936Z,
  func: 'CSVObject',
  params: {},
  traceback: [
    '    at Object.CSVObject (/app/node_modules/@ezs/basics/lib/csv-object.js:12:25)',
    '    at Engine.execWith (/app/node_modules/@ezs/core/lib/engine.js:202:40)',
    '    at /app/node_modules/@ezs/core/lib/engine.js:83:12',
    '    at drainItem (/app/node_modules/concurrent-queue/index.js:96:21)',
    '    at Immediate.drain [as _onImmediate] (/app/node_modules/concurrent-queue/index.js:77:84)',
    '    at processImmediate (node:internal/timers:476:21)'
  ],
  index: 1
}
 [default] 2024-12-20T08:48:54.957Z info: /rootAdmin/system {"method":"GET","remoteIP":"::ffff:172.17.1.3","status":200,"timestamp":"2024-12-20T08:48:54.957Z","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0"}
handleImportError Error: Error during import: Error: item #1 [CSVObject] <TypeError: data.map is not a function>
    at startImport (/app/src/api/services/import.js:121:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at processImmediate (node:internal/timers:447:9)
    at startJobImport (/app/src/api/workers/import.js:53:5)
```

**Comment by yannguillemin** [comment]
@touv : c'est moi qui faisait des tests avec ezs pour voir comment supprimer renommer lodex_pulished dans un loader...

```
sourceChunk: `{"lodex_published":"'lodex-published'"}`,
```

**Comment by touv** [comment]
ok, dans tous les cas, le message d'erreur n'était pas parlant, maintenant , il n'y aura plus d'erreur mais les données seront vides
