### ISSUE TITLE
Crash when two NQuads extended are launched

### ISSUE THREAD

**Issue by parmentf** [Inist-CNRS/lodex#371]
I just clicked on "export as NQuads étendus" on https://inist-category.data.istex.fr/home/export
I canceled that export, because I wanted the compressed one instead.

I launched the "export as NQuads étendus (Compressé)" and then, the LODEX instance was crashed.

Its logs contained that (but not sure it corresponds to that action):

```
assert.js:81
  throw new assert.AssertionError({
  ^
AssertionError: headers have already been sent
    at Object.set status [as status] (/app/node_modules/koa/lib/response.js:85:5)
    at Object.status (/app/node_modules/delegates/index.js:92:31)
    at Object.onError (/app/src/api/index.js:33:5)
    at Array.onerror (/app/node_modules/koa/lib/application.js:133:34)
    at listener (/app/node_modules/on-finished/index.js:169:15)
    at onFinish (/app/node_modules/on-finished/index.js:100:5)
    at callback (/app/node_modules/ee-first/index.js:55:10)
    at Socket.onevent (/app/node_modules/ee-first/index.js:93:5)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1284:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by parmentf** [comment]
Hints: 
- http://koajs.com/#request
- https://nodejs.org/api/net.html#net_event_close_1

**Comment by yannguillemin** [comment]
Sorry François (@parmentf), but I have to close this issue because too old. Hoping that this was resolved at the time.
