### ISSUE TITLE
Crash export extendedNquadsCompressed

### ISSUE THREAD

**Issue by QuanticPotatoes** [Inist-CNRS/lodex#436]
Gzip fault probably :

```
TypeError: Invalid non-string/buffer chunk
      at validChunk (_stream_writable.js:209:10)
      at Gzip.Writable.write (_stream_writable.js:239:21)
      at Engine.ondata (_stream_readable.js:557:20)
      at emitOne (events.js:96:13)
      at Engine.emit (events.js:191:7)
      at readableAddChunk (_stream_readable.js:178:18)
      at Engine.Readable.push (_stream_readable.js:136:10)
      at Engine.Transform.push (_stream_transform.js:128:32)
      at Engine.execWith (/app/node_modules/ezs/index.js:67:12)
      at Engine._transform (/app/node_modules/ezs/index.js:42:10)
      at Engine.Transform._read (_stream_transform.js:167:10)
      at Engine.Transform._write (_stream_transform.js:155:12)
      at doWrite (_stream_writable.js:329:12)
      at writeOrBuffer (_stream_writable.js:315:5)
      at Engine.Writable.write (_stream_writable.js:241:11)
      at Engine.ondata (_stream_readable.js:557:20)
      at emitOne (events.js:96:13)
      at Engine.emit (events.js:191:7)
      at readableAddChunk (_stream_readable.js:178:18)
      at Engine.Readable.push (_stream_readable.js:136:10)
      at Engine.Transform.push (_stream_transform.js:128:32)
      at Engine.execWith (/app/node_modules/ezs/index.js:67:12)
```
extendedNquads non compressed is fine, only difference ... gzip

**Comment by QuanticPotatoes** [comment]
zlib dependency was missing in the package.json :expressionless:
