### ISSUE TITLE
Export is broken when there are classes in the model

### ISSUE THREAD

**Issue by parmentf** [Inist-CNRS/lodex#443]
When you try to export an item of a dataset, which has classes, the loading does not end, and you get this error serverside:

```
 2017-10-20T14:01:01.158Z - info: /api/export/nquads?uri=uid%3A%2FNZ33VJ02 method=GET, remoteIP=::ffff:172.16.101.52, userAgent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36, status=200
 You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
 TypeError: Cannot read property 'startsWith' of undefined
     at getUri (/app/src/api/statements/JSONLDObject/getUri.js:19:10)
     at mergeClasses (/app/src/api/statements/JSONLDObject/mergeClasses.js:10:19)
     at merge (/app/src/api/statements/JSONLDObject/index.js:21:32)
     at currentOutputPromise.then.currentOutput (/app/src/api/statements/JSONLDObject/index.js:63:21)
     at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

**Comment by parmentf** [comment]
Strangely, we get several calls to `getUri("http://localhost:3000/uid:/NZ33VJ02")`, and then a call to `getUri(undefined)`.

That causes the `unhandledRejection` error.

**Comment by parmentf** [comment]
That's because `data.uri` is `undefined` in `mergeClasses`.

`data`:

```js
{ _id: '59e9ff140fa6a10016932cf0',
   z1GG: 'Tutoriel ISTEX',
   YzSf: 'Jeu de données relatif à la description des tutoriel ISTEX',
   G31Y: 'https://docs.google.com/drawings/d/1ZlrbVsmR3PKA-OV5GEcAoPI1cOksFGdIeiokCtJI0mk/pub?w=960&h=720',
   smEY: 'ISTEX',
   FEi8: 'Lodex Team',
   '7Puz': 'http://www.istex.fr/wp-content/uploads/2015/02/2015_Licence-type-ISTEX.pdf',
   cl1h: '2017/09/21',
   '7NfR': '2017/10/18',
   publicationDate: '2017-10-20T13:50:12.293Z' }
```

**Comment by parmentf** [comment]
In the previous calls of `mergeClasses` (those which worked), `data` was:

```js
{ _id: 59e9ff14d17c3e8371928d0c,
   uri: 'http://localhost:3000/uid:/NZ33VJ02',
   WXZZ: 'Apprendre à interroger l’API',
   ZI8w: 'http://www.inist.fr/formations/Tuto_API_ISTEX_Module_3/story.html',
   '2xNg': 'http://id.loc.gov/vocabulary/iso639-2/fre ',
   rUt1: 'Jeu de données relatif à la description des tutoriels ISTEX',
   '5uac': 'linéaire',
   hDgw: 'ressource interactive',
   '58cC': 'final',
   DkRO: 'Inist-CNRS',
   LBOI: 'concepteur pédagogique',
   bvLo: 'LOM v1.0',
   tAJu: 'text/html',
   k6zF: 'PT9M',
   kBK6: 'tutoriel',
   BqCQ: 'PT9M',
   G8zY: 'apprenant',
   YzwA: 'enseignement supérieur',
   h7Cb: 'moyen',
   '7TrR': 'false',
   DzlJ: 'false',
   u84d: 'https://creativecommons.org/licenses/by/4.0/',
   '95Dz':
    [ 'requires',
      'https://tutorial-list.data.istex.fr/ark:/67375/Q05-B29ZD5MJ-L ' ],
   End1: 'requires',
   xNFO: 'https://tutorial-list.data.istex.fr/ark:/67375/Q05-B29ZD5MJ-L ',
   R8wj: 'Caractéristiques pédagogiques du tutoriel',
   ePzl: 'PT9M',
   z6aQ: 'uid:/NZ33VJ02',
   publicationDate: 2017-10-20T13:50:12.170Z }
```

**Comment by parmentf** [comment]
It seems that a particular field yields the error: 

```js
{ _id: '59e9ff090fa6a10016932cd8',
   cover: 'dataset',
   label: 'Titre du jeu de données',
   display_in_list: true,
   display_in_resource: true,
   searchable: true,
   transformers: [ { operation: 'VALUE', args: [Object] } ],
   position: 21,
   scheme: 'http://purl.org/dc/terms/title',
   language: 'fr',
   format: { name: 'title' },
   classes: [ 'http://www.w3.org/2004/02/skos/core#ConceptScheme' ],
   name: 'z1GG' }
```

**Comment by parmentf** [comment]
Maybe because `z1GG` is a dataset field, it has no uri (obviously, it's a dataset field).

**Comment by parmentf** [comment]
When you set a default value to `data.uri`, you get this:

```
mergeClasse: data.uri=undefined, data={ _id: 59e9ff140fa6a10016932cf0,
   z1GG: 'Tutoriel ISTEX',
   YzSf: 'Jeu de données relatif à la description des tutoriel ISTEX',
   G31Y: 'https://docs.google.com/drawings/d/1ZlrbVsmR3PKA-OV5GEcAoPI1cOksFGdIeiokCtJI0mk/pub?w=960&h=720',
   smEY: 'ISTEX',
   FEi8: 'Lodex Team',
   '7Puz': 'http://www.istex.fr/wp-content/uploads/2015/02/2015_Licence-type-ISTEX.pdf',
   cl1h: '2017/09/21',
   '7NfR': '2017/10/18',
   publicationDate: 2017-10-20T13:50:12.293Z }
 getUri(http://localhost:3000/)
 getUri(http://localhost:3000/), u="http://localhost:3000/"
 output JSONLDObject: { '@id': 'http://localhost:3000/uid:/NZ33VJ02',
   '@type': '',
   WXZZ:
    { '@id': 'http://localhost:3000/uid:/NZ33VJ02/classes/WXZZ',
      '@type': [ 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#LearningObject' ],
      label: 'Apprendre à interroger l’API' },
   '@context':
    { WXZZ: { '@id': 'http://purl.org/dc/terms/title', '@language': 'fr' },
      label: { '@id': 'https://www.w3.org/2000/01/rdf-schema#label' },
      ZI8w: { '@id': 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#technicalLocation' },
      '2xNg': { '@id': 'http://purl.org/dc/terms/language' },
      rUt1:
       { '@id': 'http://purl.org/dc/terms/description',
         '@language': 'fr' },
      '5uac':
       { '@id': 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#structure',
         '@language': 'fr' },
      hDgw:
       { '@id': 'http://purl.org/dc/elements/1.1/type',
         '@language': 'fr' },
      '58cC':
       { '@id': 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#lifeCycleStatus',
         '@language': 'fr' },
      DkRO: { '@id': 'http://www.w3.org/2006/vcard/ns#organization-name' },
      LBOI:
       { '@id': 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#lifeCycleContributionRole',
         '@language': 'fr' },
      bvLo:
       { '@id': 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#metadataSchema',
         '@language': 'fr' },
      tAJu: { '@id': 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#hasTechnicalFormat' },
      kBK6:
       { '@id': 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#learningRessourceType',
         '@language': 'fr' },
      '7TrR':
       { '@id': 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#cost',
         '@language': 'en' },
      DzlJ:
       { '@id': 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#copyrightAndOtherRestrictions',
         '@language': 'en' },
      u84d: { '@id': 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#copyrightDescription' },
      End1: { '@id': 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#relationKind' },
      xNFO: { '@id': 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#hasRelatedResource' },
      '95Dz': { '@id': 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#relation' },
      BqCQ:
       { '@id': 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#educationalTypicalLearningTime',
         '@language': 'fr' },
      G8zY:
       { '@id': 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#educationalIntendedUserRole',
         '@language': 'fr' },
      YzwA:
       { '@id': 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#educationalInteractivityLevel',
         '@language': 'fr' },
      h7Cb:
       { '@id': 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#educationalDifficulty',
         '@language': 'fr' },
      R8wj: { '@id': 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#educational' },
      k6zF:
       { '@id': 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#durationValu',
         '@language': 'fr' },
      z6aQ: { '@id': 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#technicalDuration' },
      ePzl: { '@id': undefined } },
   ZI8w:
    { '@id': 'http://localhost:3000/uid:/NZ33VJ02/classes/ZI8w',
      '@type': [ 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#LearningObject' ],
      label: { '@id': 'http://www.inist.fr/formations/Tuto_API_ISTEX_Module_3/story.html' } },
   '2xNg':
    { '@id': 'http://localhost:3000/uid:/NZ33VJ02/classes/2xNg',
      '@type': [ 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#LearningObject' ],
      label: 'http://id.loc.gov/vocabulary/iso639-2/fre ' },
   rUt1:
    { '@id': 'http://localhost:3000/uid:/NZ33VJ02/classes/rUt1',
      '@type': [ 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#LearningObject' ],
      label: 'Jeu de données relatif à la description des tutoriels ISTEX' },
   '5uac':
    { '@id': 'http://localhost:3000/uid:/NZ33VJ02/classes/5uac',
      '@type': [ 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#LearningObject' ],
      label: 'linéaire' },
   hDgw:
    { '@id': 'http://localhost:3000/uid:/NZ33VJ02/classes/hDgw',
      '@type': [ 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#LearningObject' ],
      label: 'ressource interactive' },
   '58cC':
    { '@id': 'http://localhost:3000/uid:/NZ33VJ02/classes/58cC',
      '@type': [ 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#LearningObject' ],
      label: 'final' },
   DkRO:
    { '@id': 'http://localhost:3000/uid:/NZ33VJ02/classes/DkRO',
      '@type': [ '' ],
      label: 'Inist-CNRS' },
   LBOI:
    { '@id': 'http://localhost:3000/uid:/NZ33VJ02/classes/LBOI',
      '@type': [ 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#LearningObject' ],
      label: 'concepteur pédagogique' },
   bvLo:
    { '@id': 'http://localhost:3000/uid:/NZ33VJ02/classes/bvLo',
      '@type': [ 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#LearningObject' ],
      label: 'LOM v1.0' },
   tAJu: 'text/html',
   kBK6:
    { '@id': 'http://localhost:3000/uid:/NZ33VJ02/classes/kBK6',
      '@type': [ 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#LearningObject' ],
      label: 'tutoriel' },
   '7TrR':
    { '@id': 'http://localhost:3000/uid:/NZ33VJ02/classes/7TrR',
      '@type': [ 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#LearningObject' ],
      label: 'false' },
   DzlJ:
    { '@id': 'http://localhost:3000/uid:/NZ33VJ02/classes/DzlJ',
      '@type': [ 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#LearningObject' ],
      label: 'false' },
   u84d:
    { '@id': 'http://localhost:3000/uid:/NZ33VJ02/classes/u84d',
      '@type': [ 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#LearningObject' ],
      label: { '@id': 'https://creativecommons.org/licenses/by/4.0/' } },
   '95Dz':
    [ { '@id': 'http://localhost:3000/uid:/NZ33VJ02/compose/95Dz',
        '@type': [Object],
        End1: 'requires' },
      { '@id': 'http://localhost:3000/uid:/NZ33VJ02/compose/95Dz',
        '@type': [Object],
        xNFO: [Object] } ],
   xNFO:
    { '@id': 'http://localhost:3000/uid:/NZ33VJ02/classes/xNFO',
      '@type': [ 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#LearningObject' ],
      label: 'https://tutorial-list.data.istex.fr/ark:/67375/Q05-B29ZD5MJ-L ' },
   R8wj:
    [ { '@id': 'http://localhost:3000/uid:/NZ33VJ02/compose/R8wj',
        '@type': [Object],
        BqCQ: 'PT9M' },
      { '@id': 'http://localhost:3000/uid:/NZ33VJ02/compose/R8wj',
        '@type': [Object],
        G8zY: 'apprenant' },
      { '@id': 'http://localhost:3000/uid:/NZ33VJ02/compose/R8wj',
        '@type': [Object],
        YzwA: 'enseignement supérieur' },
      { '@id': 'http://localhost:3000/uid:/NZ33VJ02/compose/R8wj',
        '@type': [Object],
        h7Cb: 'moyen' } ],
   ePzl:
    [ { '@id': 'http://localhost:3000/uid:/NZ33VJ02/compose/ePzl',
        '@type': [Object],
        k6zF: 'PT9M' },
      { '@id': 'http://localhost:3000/uid:/NZ33VJ02/compose/ePzl',
        '@type': [Object],
        z6aQ: [Object] } ],
   z6aQ:
    { '@id': 'http://localhost:3000/uid:/NZ33VJ02/classes/z6aQ',
      '@type': [ 'http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#LearningObject' ],
      label: { '@id': 'undefined/uid:/NZ33VJ02' } },
   dataset:
    { z1GG:
       { '@id': 'http://localhost:3000//classes/z1GG',
         '@type': [Object],
         label: 'Tutoriel ISTEX' },
      '@context':
       { z1GG: [Object],
         label: [Object],
         YzSf: [Object],
         G31Y: [Object],
         smEY: [Object],
         FEi8: [Object],
         '7Puz': [Object],
         cl1h: [Object],
         '7NfR': [Object] },
      YzSf:
       { '@id': 'http://localhost:3000//classes/YzSf',
         '@type': [Object],
         label: 'Jeu de données relatif à la description des tutoriel ISTEX' },
      G31Y:
       { '@id': 'http://localhost:3000//classes/G31Y',
         '@type': [Object],
         label: [Object] },
      smEY:
       { '@id': 'http://localhost:3000//classes/smEY',
         '@type': [Object],
         label: 'ISTEX' },
      FEi8:
       { '@id': 'http://localhost:3000//classes/FEi8',
         '@type': [Object],
         label: 'Lodex Team' },
      '7Puz':
       { '@id': 'http://localhost:3000//classes/7Puz',
         '@type': [Object],
         label: [Object] },
      cl1h:
       { '@id': 'http://localhost:3000//classes/cl1h',
         '@type': [Object],
         label: '2017/09/21' },
      '7NfR':
       { '@id': 'http://localhost:3000//classes/7NfR',
         '@type': [Object],
         label: '2017/10/18' } } }
 You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
 Error
     at /app/node_modules/jsonld/js/jsonld.js:952:23
     at /app/node_modules/jsonld/js/jsonld.js:365:16
     at finished (/app/node_modules/jsonld/js/jsonld.js:6791:7)
     at retrieve (/app/node_modules/jsonld/js/jsonld.js:6797:14)
     at _retrieveContextUrls (/app/node_modules/jsonld/js/jsonld.js:6896:3)
     at expand (/app/node_modules/jsonld/js/jsonld.js:324:5)
     at /app/node_modules/jsonld/js/jsonld.js:303:5
     at _combinedTickCallback (internal/process/next_tick.js:73:7)
     at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by parmentf** [comment]
In JSONLDObject's `output.@context`, there is: 

```json
"ePzl": { "@id": undefined }
```
which is not valid JSON!

The matching value is: 

```json
"ePzl":
    [ { "@id": "http://localhost:3000/uid:/NZ33VJ02/compose/ePzl",
        "@type": [Object],
        "k6zF": "PT9M" },
      { "@id": "http://localhost:3000/uid:/NZ33VJ02/compose/ePzl",
        "@type": [Object],
        "z6aQ": [Object] } ]
```
It's a composed field.

**Comment by parmentf** [comment]
Other contexts are like:

```json
"R8wj": { "@id": "http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#educational" },
"k6zF":
       { "@id": "http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#durationValu",
         "@language": "fr" },
"z6aQ": { "@id": "http://data.opendiscoveryspace.eu/lom_ontology_ods.owl#technicalDuration" },
```

Oh. That's because the `ePzl` field has no scheme (see the following schema):

![image](https://user-images.githubusercontent.com/595509/31831368-87a0802c-b5c3-11e7-8ccc-522da3e16a8f.png)

`ePzl` is `lom:Duration`, and, because its relation to the resource is inverted, has no scheme.

![image](https://user-images.githubusercontent.com/595509/31831560-346be5c6-b5c4-11e7-8aa8-518a355d2eb8.png)

I'll delete this field, and this if export works.

**Comment by parmentf** [comment]
Export works, but I'm unable to write a working test for that.

**Comment by touv** [comment]
I don't understand, is it fixed ?

**Comment by parmentf** [comment]
Not yet. I wrote a test.
Trying to make it pass, now.

**Comment by parmentf** [comment]
The example I took was not a correct one (tutorials): all classes are domains, not ranges.
I have to find one better.
